### model
model_name_or_path: /root/shared-nvme/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B-Int4-W4A16

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: dynamic_dataset
dataset_dir: ./data
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../novel_data/lora_train_output/lora_test_result
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
